### ISSUE TITLE
I couldn't get it to work

### ISSUE THREAD

**Issue by welpdx** [ChrisBeatrez/Soundcloud-Likes-Scraper-GUI#1]
After installing the dependencies, I get the following error:

```cmd

C:\Repos\Soundcloud-Likes-Scraper-GUI>python main.py

DevTools listening on ws://127.0.0.1:65081/devtools/browser/773fce6f-4e77-44e3-aa17-2ff9b08ca4eb
[0623/150458.243:INFO:CONSOLE(33)] "You like to look under the hood? Why not help us build the engine? https://soundcloud.com/jobs", source: https://a-v2.sndcdn.com/assets/49-d3ed48e3.js (33)
[0623/150459.954:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0623/150459.955:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
Exception in thread Thread-1 (scrape):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Repos\Soundcloud-Likes-Scraper-GUI\main.py", line 38, in scrape
    BeautifulSoup(html, 'lxml')
  File "C:\Python310\lib\site-packages\bs4\__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

```

Thanks

Edit: additional information
I didn't do the build using setup.py, I just went straight into running the code via `python main.py`
I didn't change code other than using the `chromedriver_autoinstaller` module to run my version of chrome. 
Did test on test url by entering nothing but `scrapertest` in text Field.

**Comment by ChrisBeatrez** [comment]
Import the project into your ide. Make sure all the imports and packages are installed. Make sure to install lxml package based off your error.  It should work after that.

**Comment by welpdx** [comment]
Thanks, I realized that I didn't have lxml module installed. After installation, the error looks like this now:
```cmd
C:\Repos\Soundcloud-Likes-Scraper-GUI>python main.py

DevTools listening on ws://127.0.0.1:49992/devtools/browser/d87617a2-0154-452d-bf63-a6ccbb449d4e
[0623/161653.994:INFO:CONSOLE(33)] "You like to look under the hood? Why not help us build the engine? https://soundcloud.com/jobs", source: https://a-v2.sndcdn.com/assets/49-d3ed48e3.js (33)
[0623/161655.847:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
[0623/161655.847:ERROR:web_contents_delegate.cc(232)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
```

Do you have this error when you run your chromedriver?

**Comment by ChrisBeatrez** [comment]
No I have not seen this error before. Is the gui running when you start the program? If it is, what user are you typing in to try and scrape? Make sure you have the latest version of chrome and chromedriver. I also placed chromedriver in this windows file directory. C:\Windows

Edit: I noticed in your first comment you mention chromedriver_autoinstaller, Im not sure what that is exactly but make sure to download chromedriver [here](https://chromedriver.chromium.org/downloads)
